# Generated by Django 5.2.8 on 2026-08-28 17:36

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0044_checkinsettings'),
        ('properties', '0043_managementcompany_finances_managed_internally'),
        ('staff', '0012_staffrole_can_view_finance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clean_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('meet_greet_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('cleaning_task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memo', to='staff.cleaningtask')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memos', to='properties.property')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Memo',
                'verbose_name_plural': 'Memos',
                'db_table': 'finance_memos',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AdHocService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ad_hoc_services', to='properties.property')),
                ('memo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_hoc_services', to='finance.memo')),
            ],
            options={
                'verbose_name': 'Ad-hoc Service',
                'verbose_name_plural': 'Ad-hoc Services',
                'db_table': 'finance_ad_hoc_services',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PayoutRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout_record', to='bookings.booking')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payout Record',
                'verbose_name_plural': 'Payout Records',
                'db_table': 'finance_payout_records',
                'ordering': ('-paid_at',),
            },
        ),
    ]
