# Generated by Django 5.2.8 on 2026-09-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_depositreturn'),
    ]

    operations = [
        migrations.CreateModel(
            name='SageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(blank=True, max_length=200, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=200, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('default_tax_rate_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Sage Settings',
                'verbose_name_plural': 'Sage Settings',
                'db_table': 'finance_sage_settings',
            },
        ),
        migrations.AddField(
            model_name='memo',
            name='sage_invoice_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memo',
            name='sage_invoice_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
