# Generated by Django 5.2.8 on 2026-09-09 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0059_bookingsettings_cleaning_gap_nights_per_block_day'),
        ('finance', '0003_sagesettings_memo_sage_invoice_error_and_more'),
        ('properties', '0060_owner_secondary_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='management_fee_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memo',
            name='management_fee_paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sagesettings',
            name='commission_tax_rate_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='OwnerInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('commission_payout', 'Rental commission (per payout)'), ('cleans_monthly', 'Cleans & meet-greet (monthly)'), ('commission_monthly', 'Rental commission (monthly)'), ('combined_monthly', 'Commission + cleans (monthly)')], max_length=20)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cleans_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sage_invoice_id', models.CharField(blank=True, max_length=50, null=True)),
                ('sage_invoice_error', models.TextField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, choices=[('revolut', 'Revolut'), ('wise', 'Wise')], max_length=10, null=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('paid', 'Paid'), ('declined', 'Declined'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], max_length=15, null=True)),
                ('revolut_order_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('revolut_checkout_url', models.URLField(blank=True, null=True)),
                ('last_event_type', models.CharField(blank=True, max_length=100, null=True)),
                ('in_progress_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('bookings', models.ManyToManyField(blank=True, related_name='owner_invoices', to='bookings.booking')),
                ('memos', models.ManyToManyField(blank=True, related_name='owner_invoices', to='finance.memo')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='properties.owner')),
                ('payout_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commission_invoice', to='finance.payoutrecord')),
            ],
            options={
                'verbose_name': 'Owner Invoice',
                'verbose_name_plural': 'Owner Invoices',
                'db_table': 'finance_owner_invoices',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('period_start__isnull', False)), fields=('owner', 'kind', 'period_start'), name='unique_owner_kind_period')],
            },
        ),
    ]
