# Generated by Django 5.2.8 on 2026-09-09 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_memo_management_fee_paid_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sagesettings',
            name='commission_tax_rate_id',
        ),
    ]
