# Generated by Django 5.2.8 on 2026-09-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_remove_sagesettings_commission_tax_rate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerinvoice',
            name='kind',
            field=models.CharField(choices=[('commission_payout', 'Rental commission (per payout)'), ('cleans_monthly', 'Cleans & meet-greet (monthly)'), ('commission_monthly', 'Rental commission (monthly)'), ('combined_monthly', 'Commission + cleans (monthly)'), ('cleans_informal_monthly', 'Cleans & meet-greet (informal monthly)')], max_length=30),
        ),
    ]
