# Generated by Django 6.0.1 on 2026-09-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_ownerinvoice_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutrecord',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payoutrecord',
            name='in_progress_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payoutrecord',
            name='last_event_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payoutrecord',
            name='provider',
            field=models.CharField(blank=True, choices=[('revolut', 'Revolut'), ('wise', 'Wise')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='payoutrecord',
            name='revolut_transfer_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payoutrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('paid', 'Paid'), ('declined', 'Declined'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='paid', max_length=15),
        ),
    ]
