# Generated by Django 5.2.8 on 2026-08-22 19:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0027_alter_booking_ical_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Deduction',
                'verbose_name_plural': 'Deductions',
                'db_table': 'staff_deductions',
                'ordering': ('-date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='OwnerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('EUR', 'EUR'), ('GBP', 'GBP')], max_length=3)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_payments', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Owner Payment',
                'verbose_name_plural': 'Owner Payments',
                'db_table': 'staff_owner_payments',
                'ordering': ('-date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='TaskHistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_history', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Task History Entry',
                'verbose_name_plural': 'Task History Entries',
                'db_table': 'staff_task_history_entries',
                'ordering': ('-created_at',),
            },
        ),
    ]
