# Generated by Django 5.2.8 on 2026-08-25 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerpayment',
            name='currency',
        ),
    ]
