# Generated by Django 5.2.8 on 2026-08-26 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0039_extra_mid_stay_clean_date'),
        ('staff', '0004_staffrole_staffprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staffrole',
            name='can_view_cleaning_rota',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CleaningTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('turnover', 'Turnover'), ('mid_stay', 'Mid-stay')], max_length=20)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleaning_tasks', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_tasks', to='bookings.booking')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cleaning Task',
                'verbose_name_plural': 'Cleaning Tasks',
                'db_table': 'staff_cleaning_tasks',
                'ordering': ('date', 'booking__property__title'),
                'unique_together': {('booking', 'task_type')},
            },
        ),
    ]
