# Generated by Django 5.2.8 on 2026-08-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_staffrole_can_view_cleaning_rota_cleaningtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningtask',
            name='auto_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cleaningtask',
            name='manually_scheduled',
            field=models.BooleanField(default=False),
        ),
    ]
