# Generated by Django 5.2.8 on 2026-08-26 20:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_cleaningtask_auto_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staffrole',
            name='is_cleaning_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='cleaningtask',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='cleaningtask',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='cleaning_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
