# Generated by Django 5.2.8 on 2026-08-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_staffrole_is_cleaning_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningtask',
            name='team',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Group 1'), (2, 'Group 2'), (3, 'Group 3')], default=1),
        ),
    ]
