# Generated by Django 5.2.8 on 2026-08-27 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_cleaningtask_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningtask',
            name='dismissed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cleaningtask',
            name='dismissed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cleaningtask',
            name='dismissed_reason',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('gap_closed', 'Gap closed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cleaningtask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('dismissed', 'Dismissed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='cleaningtask',
            name='task_type',
            field=models.CharField(choices=[('turnover', 'Turnover'), ('mid_stay', 'Mid-stay'), ('freshen', 'Freshen')], max_length=20),
        ),
    ]
