# Generated by Django 5.2.8 on 2026-08-27 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0044_checkinsettings'),
        ('staff', '0009_cleaningtask_dismissed_at_cleaningtask_dismissed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staffrole',
            name='can_view_checkins_calendar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffrole',
            name='is_checkin_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('arrival', 'Arrival'), ('key_box', 'Key box'), ('welcome_visit', 'Welcome visit')], max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('manually_scheduled', models.BooleanField(default=False)),
                ('auto_time', models.TimeField(blank=True, null=True)),
                ('extras_collected', models.BooleanField(default=False)),
                ('deposit_collected', models.BooleanField(default=False)),
                ('deposit_returned', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='checkins', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='bookings.booking')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Check-in',
                'verbose_name_plural': 'Check-ins',
                'db_table': 'staff_checkins',
                'ordering': ('date', 'time', 'booking__property__title'),
                'unique_together': {('booking', 'task_type')},
            },
        ),
    ]
