# Generated by Django 5.2.8 on 2026-08-28 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_staffrole_can_view_checkins_calendar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='deposit_returned',
        ),
    ]
