# Generated by Django 5.2.8 on 2026-08-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_remove_checkin_deposit_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffrole',
            name='can_view_finance',
            field=models.BooleanField(default=False),
        ),
    ]
