# Generated by Django 5.2.8 on 2026-08-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_staffrole_can_view_finance'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffrole',
            name='can_view_reports',
            field=models.BooleanField(default=False),
        ),
    ]
