# Generated by Django 5.2.8 on 2026-09-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_staffrole_can_view_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffrole',
            name='can_send_emails',
            field=models.BooleanField(default=False),
        ),
    ]
