# Generated by Django 5.2.8 on 2026-09-05 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_staffrole_can_send_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('pt', 'Português')], default='en', max_length=2),
        ),
    ]
