# Generated by Django 5.2.8 on 2026-09-08 22:36

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0058_bookingsettings_tourist_tax_season_end_month_and_more'),
        ('staff', '0015_staffprofile_preferred_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LateCheckoutGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(blank=True, choices=[(datetime.time(11, 0), '11:00'), (datetime.time(12, 0), '12:00')], null=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('block_booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bookings.booking')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='late_checkout_grant', to='bookings.booking')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Late Check-out Grant',
                'verbose_name_plural': 'Late Check-out Grants',
                'db_table': 'staff_late_checkout_grants',
            },
        ),
    ]
