# Generated by Django 5.2.8 on 2026-09-09 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0059_bookingsettings_cleaning_gap_nights_per_block_day'),
        ('staff', '0016_latecheckoutgrant'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningGapBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block_booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bookings.booking')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_gap_block', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Cleaning Gap Block',
                'verbose_name_plural': 'Cleaning Gap Blocks',
                'db_table': 'staff_cleaning_gap_blocks',
            },
        ),
    ]
