# Generated by Django 5.2.8 on 2026-09-16 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0067_bookingsettings_max_advance_booking_months'),
        ('staff', '0017_cleaninggapblock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('maintenance', 'Maintenance work'), ('sale_or_ownership', 'Potential sale or ownership change'), ('other', 'Other')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='property_block', to='bookings.booking')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property Block',
                'verbose_name_plural': 'Property Blocks',
                'db_table': 'staff_property_blocks',
                'ordering': ('-created_at',),
            },
        ),
    ]
