# Generated by Django 5.2.8 on 2026-03-08 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accountant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Property Accountant',
                'verbose_name_plural': 'Property Accountants',
                'db_table': 'property_accountants',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('coordinates', models.CharField(max_length=100)),
                ('map_link', models.URLField()),
                ('directions', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('zip_code', models.CharField(max_length=20)),
                ('nearest_bins', models.TextField(blank=True, null=True)),
                ('nearest_corner_shop', models.TextField(blank=True, null=True)),
                ('nearest_supermarket', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Property Location',
                'verbose_name_plural': 'Property Locations',
                'db_table': 'property_locations',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('head_name', models.CharField(max_length=200)),
                ('head_email', models.EmailField(max_length=254, unique=True)),
                ('head_phone', models.CharField(max_length=50, unique=True)),
                ('maintenance', models.CharField(max_length=200)),
                ('maintenance_phone', models.CharField(max_length=50)),
                ('maintenance_email', models.EmailField(max_length=254)),
                ('liaison_name', models.CharField(max_length=200)),
                ('liaison_phone', models.CharField(max_length=50)),
                ('liaison_email', models.EmailField(max_length=254)),
                ('cleaning_name', models.CharField(max_length=200)),
                ('cleaning_phone', models.CharField(max_length=50)),
                ('cleaning_email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Property Manager',
                'verbose_name_plural': 'Property Managers',
                'db_table': 'property_managers',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('nif_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('default_clean', models.BooleanField()),
                ('default_meet_greet', models.BooleanField()),
                ('takes_euros', models.BooleanField()),
                ('takes_pounds', models.BooleanField()),
                ('wants_accounting', models.BooleanField()),
                ('cleans_are_invoiced', models.BooleanField()),
                ('rental_commissions_are_invoiced', models.BooleanField()),
                ('is_paid_regularly', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Property Owner',
                'verbose_name_plural': 'Property Owners',
                'db_table': 'property_owners',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('name', models.CharField(default='Undefined Price List', max_length=200)),
                ('january', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('february', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('march', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('april', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('may', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('june', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('july', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('august', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('september', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('october', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('november', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('december', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('festive', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('early_winter_monthly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('late_winter_monthly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Property Price',
                'verbose_name_plural': 'Property Prices',
                'db_table': 'property_prices',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed Property', max_length=200, unique=True)),
                ('short_name', models.CharField(default='unnamed-property', max_length=100, unique=True)),
                ('al_number', models.IntegerField(blank=True, null=True)),
                ('we_book', models.BooleanField(default=False)),
                ('booking_com_name', models.CharField(blank=True, max_length=200, null=True)),
                ('airbnb_name', models.CharField(blank=True, max_length=200, null=True)),
                ('we_clean', models.BooleanField(default=False)),
                ('standard_cleaning_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('send_owner_booking_forms', models.BooleanField(default=False)),
                ('accountant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.accountant')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.location')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.manager')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.owner')),
                ('price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.price')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'db_table': 'properties',
            },
        ),
        migrations.CreateModel(
            name='SEFDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade_hoteleira', models.CharField(blank=True, max_length=200, null=True)),
                ('estabelecimento', models.CharField(blank=True, max_length=200, null=True)),
                ('chave_de_autenticacao', models.CharField(blank=True, max_length=200, null=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sef_details', to='properties.property')),
            ],
            options={
                'verbose_name': 'Property SEF Detail',
                'verbose_name_plural': 'Property SEF Details',
                'db_table': 'property_sef_details',
            },
        ),
        migrations.CreateModel(
            name='Spec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_listed', models.BooleanField()),
                ('is_sea_view', models.BooleanField()),
                ('is_upper_floor', models.BooleanField()),
                ('is_beachfront', models.BooleanField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('square_metres', models.IntegerField()),
                ('max_guests', models.IntegerField()),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='properties.property')),
            ],
            options={
                'verbose_name': 'Property Specification',
                'verbose_name_plural': 'Property Specifications',
                'db_table': 'property_specs',
            },
        ),
    ]
