# Generated by Django 5.2.8 on 2026-08-14 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='finance_email',
            field=models.EmailField(default='N/A', max_length=254),
        ),
        migrations.AddField(
            model_name='manager',
            name='finance_name',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='manager',
            name='finance_phone',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
