# Generated by Django 5.2.8 on 2026-03-08 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spec',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spec',
            name='max_adults',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='spec',
            name='minimum_nights',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='spec',
            name='max_guests',
            field=models.IntegerField(default=4),
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bathtub_and_shower', models.BooleanField(default=True)),
                ('walk_in_shower', models.BooleanField(default=False)),
                ('hairdryer', models.BooleanField(default=True)),
                ('double_bed', models.BooleanField(default=True)),
                ('single_beds', models.IntegerField(default=0)),
                ('bed_size', models.TextField(default='160 x 200')),
                ('washing_machine', models.BooleanField(default=True)),
                ('dryer', models.BooleanField(default=False)),
                ('iron', models.BooleanField(default=True)),
                ('ironing_board', models.BooleanField(default=True)),
                ('wifi', models.BooleanField(default=True)),
                ('tv', models.BooleanField(default=True)),
                ('air_conditioning', models.BooleanField(default=True)),
                ('heating', models.BooleanField(default=True)),
                ('kitchen', models.BooleanField(default=True)),
                ('oven', models.BooleanField(default=True)),
                ('microwave', models.BooleanField(default=True)),
                ('fridge', models.BooleanField(default=True)),
                ('freezer', models.BooleanField(default=True)),
                ('dishwasher', models.BooleanField(default=True)),
                ('barbecue', models.BooleanField(default=False)),
                ('pool', models.BooleanField(default=True)),
                ('hot_tub', models.BooleanField(default=False)),
                ('garden', models.BooleanField(default=False)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='properties.property')),
            ],
            options={
                'verbose_name': 'Property Amenity',
                'verbose_name_plural': 'Property Amenities',
                'db_table': 'property_amenities',
            },
        ),
    ]
