# Generated by Django 5.2.8 on 2026-03-08 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_spec_description_spec_max_adults_spec_minimum_nights_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='name',
        ),
    ]
