# Generated by Django 5.2.8 on 2026-08-15 13:50

import django.db.models.deletion
import properties.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_manager_finance_email_manager_finance_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='hob',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='amenity',
            name='kettle',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='amenity',
            name='safe',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='amenity',
            name='toaster',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='LocationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=properties.utils.location_image_path)),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.location')),
            ],
            options={
                'verbose_name': 'Property Location Image',
                'verbose_name_plural': 'Property Location Images',
                'db_table': 'property_location_images',
            },
        ),
        migrations.CreateModel(
            name='LocationSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sea_views', models.BooleanField(default=False)),
                ('pool', models.BooleanField(default=True)),
                ('lift', models.BooleanField(default=True)),
                ('beachfront', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=True)),
                ('private_parking', models.BooleanField()),
                ('street_parking', models.BooleanField(default=False)),
                ('gym', models.BooleanField(default=False)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='properties.location')),
            ],
            options={
                'verbose_name': 'Property Location Specification',
                'verbose_name_plural': 'Property Location Specifications',
                'db_table': 'property_location_specs',
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=properties.utils.property_image_path)),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'verbose_name': 'Property Image',
                'verbose_name_plural': 'Property Images',
                'db_table': 'property_images',
            },
        ),
    ]
