# Generated by Django 5.2.8 on 2026-05-20 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_remove_amenity_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='address',
            new_name='location',
        ),
    ]
