# Generated by Django 5.2.8 on 2026-08-15 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_amenity_hob_amenity_kettle_amenity_safe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='properties.property'),
        ),
        migrations.DeleteModel(
            name='Spec',
        ),
        migrations.CreateModel(
            name='PropertySpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sea_view', models.BooleanField()),
                ('is_pool_view', models.BooleanField()),
                ('is_upper_floor', models.BooleanField()),
                ('is_beachfront', models.BooleanField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('half_bathrooms', models.IntegerField()),
                ('square_metres', models.IntegerField(default=60)),
                ('minimum_nights', models.IntegerField(default=4)),
                ('max_adults', models.IntegerField(default=4)),
                ('max_guests', models.IntegerField(default=4)),
                ('children_allowed', models.BooleanField(default=True)),
                ('pets_allowed', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='properties.property')),
            ],
            options={
                'verbose_name': 'Property Specification',
                'verbose_name_plural': 'Property Specifications',
                'db_table': 'property_specs',
            },
        ),
    ]
