# Generated by Django 5.2.8 on 2026-08-15 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_amenity_property_propertyspec_delete_spec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icallink',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ical_links', to='properties.property'),
        ),
    ]
