# Generated by Django 5.2.8 on 2026-05-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_rename_address_property_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='name',
        ),
        migrations.RemoveField(
            model_name='property',
            name='short_name',
        ),
        migrations.AddField(
            model_name='property',
            name='short_title',
            field=models.CharField(default='untitled-property', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='property',
            name='title',
            field=models.CharField(default='Untitled Property', max_length=200, unique=True),
        ),
    ]
