# Generated by Django 5.2.8 on 2026-05-20 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_remove_property_name_remove_property_short_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='short_title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
