# Generated by Django 5.2.8 on 2026-08-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_icallink_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icallink',
            name='ical_source',
            field=models.CharField(blank=True, choices=[('airbnb', 'Airbnb'), ('booking.com', 'Booking.com'), ('vrbo', 'Vrbo')], max_length=20, null=True),
        ),
    ]
