# Generated by Django 5.2.8 on 2026-08-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_icallink_ical_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationspec',
            name='private_parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='locationspec',
            name='street_parking',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='propertyspec',
            name='bathrooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='propertyspec',
            name='bedrooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='propertyspec',
            name='half_bathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='propertyspec',
            name='is_beachfront',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='propertyspec',
            name='is_pool_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='propertyspec',
            name='is_sea_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='propertyspec',
            name='is_upper_floor',
            field=models.BooleanField(default=False),
        ),
    ]
