# Generated by Django 5.2.8 on 2026-06-04 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_property_short_title_alter_property_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='airbnb_name',
            new_name='airbnb_title',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='booking_com_name',
            new_name='booking_com_title',
        ),
    ]
