# Generated by Django 5.2.8 on 2026-08-15 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_alter_locationspec_private_parking_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationimage',
            options={'ordering': ['priority'], 'verbose_name': 'Property Location Image', 'verbose_name_plural': 'Property Location Images'},
        ),
    ]
