# Generated by Django 5.2.8 on 2026-08-15 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_alter_locationimage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'ordering': ['priority'], 'verbose_name': 'Property Image', 'verbose_name_plural': 'Property Images'},
        ),
    ]
