# Generated by Django 5.2.8 on 2026-08-15 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_alter_propertyimage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiet_hours_start', models.TimeField()),
                ('quiet_hours_end', models.TimeField()),
                ('pool_hours_start', models.TimeField()),
                ('pool_hours_end', models.TimeField()),
                ('pool_rules', models.TextField(blank=True, null=True)),
                ('condominium_rules', models.TextField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='properties.location')),
            ],
            options={
                'verbose_name': 'Property Location Rule',
                'verbose_name_plural': 'Property Location Rules',
                'db_table': 'property_location_rules',
            },
        ),
    ]
