# Generated by Django 5.2.8 on 2026-08-15 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_locationrules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationrules',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='properties.location'),
        ),
    ]
