# Generated by Django 6.0.1 on 2026-08-17 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_alter_locationrules_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='last_minute_discount_days',
            field=models.PositiveIntegerField(default=7, help_text='Number of days before arrival within which the last-minute discount applies.'),
        ),
        migrations.AddField(
            model_name='price',
            name='last_minute_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount applied when booking within the last-minute window, as a percentage.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='price',
            name='weekly_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount applied to stays of 7 or more nights, as a percentage.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
