# Generated by Django 6.0.1 on 2026-08-17 17:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_price_last_minute_discount_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='monthly_discount_min_nights',
            field=models.PositiveIntegerField(default=28, help_text='Minimum number of nights a stay must be for the monthly discount to apply.'),
        ),
        migrations.AddField(
            model_name='price',
            name='monthly_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount applied to stays of at least monthly_discount_min_nights nights, as a percentage.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
