# Generated by Django 6.0.1 on 2026-08-17 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_price_monthly_discount_min_nights_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='is_special_rate',
        ),
    ]
