# Generated by Django 6.0.1 on 2026-08-17 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_remove_price_is_special_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='end_date',
            field=models.DateField(verbose_name='end'),
        ),
        migrations.AlterField(
            model_name='price',
            name='last_minute_discount_days',
            field=models.PositiveIntegerField(default=7, help_text='Number of days before arrival within which the last-minute discount applies.', verbose_name='last-min days'),
        ),
        migrations.AlterField(
            model_name='price',
            name='last_minute_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount applied when booking within the last-minute window, as a percentage.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='last-min %'),
        ),
        migrations.AlterField(
            model_name='price',
            name='monthly_discount_min_nights',
            field=models.PositiveIntegerField(default=28, help_text='Minimum number of nights a stay must be for the monthly discount to apply.', verbose_name='min nights'),
        ),
        migrations.AlterField(
            model_name='price',
            name='monthly_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount applied to stays of at least monthly_discount_min_nights nights, as a percentage.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='monthly %'),
        ),
        migrations.AlterField(
            model_name='price',
            name='start_date',
            field=models.DateField(verbose_name='start'),
        ),
        migrations.AlterField(
            model_name='price',
            name='weekly_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount applied to stays of 7 or more nights, as a percentage.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='weekly %'),
        ),
    ]
