# Generated by Django 6.0.1 on 2026-08-17 18:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_alter_price_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='extra_adult_rate',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Charge per night for each adult beyond the first 2.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='extra adult'),
        ),
        migrations.AddField(
            model_name='price',
            name='extra_child_rate',
            field=models.DecimalField(decimal_places=2, default=5, help_text='Charge per night for each child.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='extra child'),
        ),
    ]
