# Generated by Django 6.0.1 on 2026-08-17 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_price_extra_adult_rate_price_extra_child_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='monthly_discount_min_nights',
        ),
        migrations.AlterField(
            model_name='price',
            name='monthly_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount applied to stays meeting the site-wide monthly-stay minimum (see Booking Settings), as a percentage.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='monthly %'),
        ),
    ]
