# Generated by Django 5.2.8 on 2026-08-22 18:21

import secrets

from django.db import migrations, models


def backfill_ical_export_tokens(apps, schema_editor):
    Property = apps.get_model('properties', 'Property')
    for property in Property.objects.filter(ical_export_token__isnull=True):
        property.ical_export_token = secrets.token_urlsafe(32)
        property.save(update_fields=['ical_export_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_remove_price_monthly_discount_min_nights_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='ical_export_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.RunPython(backfill_ical_export_tokens, migrations.RunPython.noop),
    ]
