# Generated by Django 5.2.8 on 2026-08-23 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_property_ical_export_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='name',
        ),
    ]
