# Generated by Django 5.2.8 on 2026-08-23 20:47

import django.db.models.deletion
from django.db import migrations, models


def backfill_property_ownership(apps, schema_editor):
    """One NULL-start/NULL-end PropertyOwnership row per Property that already has an owner -
    NULL means 'owned since before klt-web tracked ownership history', per the confirmed backfill
    decision (we have no real historical handover dates to backfill with). apps.get_model()
    returns a frozen historical model with no custom methods, so this can't call
    PropertyOwnership.record_initial_ownership() - plain field assignment only."""
    Property = apps.get_model('properties', 'Property')
    PropertyOwnership = apps.get_model('properties', 'PropertyOwnership')
    for property in Property.objects.filter(owner_id__isnull=False):
        PropertyOwnership.objects.create(
            property_id=property.pk, owner_id=property.owner_id,
            start_date=None, end_date=None,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0019_remove_price_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ownership_history', to='properties.owner')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_history', to='properties.property')),
            ],
            options={
                'verbose_name': 'Property Ownership',
                'verbose_name_plural': 'Property Ownership History',
                'db_table': 'property_ownership_history',
                'ordering': [models.OrderBy(models.F('start_date'), descending=True, nulls_last=True)],
            },
        ),
        migrations.RunPython(backfill_property_ownership, migrations.RunPython.noop),
    ]
