# Generated by Django 5.2.8 on 2026-08-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0020_propertyownership'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='bath_towels_per_guest',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='amenity',
            name='beach_towels_per_guest',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='amenity',
            name='clothes_horse',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='amenity',
            name='coffee_machine',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='amenity',
            name='hand_towels_per_guest',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='amenity',
            name='mop_and_bucket',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='amenity',
            name='vacuum_cleaner',
            field=models.BooleanField(default=True),
        ),
    ]
