# Generated by Django 5.2.8 on 2026-08-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0021_amenity_bath_towels_per_guest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('contacts', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='management_company', to='properties.manager')),
            ],
            options={
                'verbose_name': 'Management Company',
                'verbose_name_plural': 'Management Companies',
                'db_table': 'management_companies',
            },
        ),
    ]
