# Generated by Django 5.2.8 on 2026-08-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0022_managementcompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='booking_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_properties', to='properties.managementcompany'),
        ),
        migrations.AddField(
            model_name='property',
            name='cleaning_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleaned_properties', to='properties.managementcompany'),
        ),
    ]
