# Generated by Django 5.2.8 on 2026-08-25

from django.db import migrations


def seed_and_backfill(apps, schema_editor):
    """Seed the one real ManagementCompany (KLT Property Services Lda.) and backfill
    Property.booking_company/cleaning_company from the we_book/we_clean booleans they're about to
    replace - True maps to this company, False stays NULL (untracked external party). Links to
    the one existing Manager row for its contacts rather than duplicating the company name as a
    second freestanding string. apps.get_model() returns frozen historical models - plain field
    assignment only, no custom methods."""
    Manager = apps.get_model('properties', 'Manager')
    ManagementCompany = apps.get_model('properties', 'ManagementCompany')
    Property = apps.get_model('properties', 'Property')

    manager = Manager.objects.first()
    company = ManagementCompany.objects.create(
        name='KLT Property Services Lda.',
        contacts_id=manager.pk if manager else None,
    )
    Property.objects.filter(we_book=True).update(booking_company_id=company.pk)
    Property.objects.filter(we_clean=True).update(cleaning_company_id=company.pk)


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0023_property_booking_company_property_cleaning_company'),
    ]

    operations = [
        migrations.RunPython(seed_and_backfill, migrations.RunPython.noop),
    ]
