# Generated by Django 5.2.8 on 2026-08-25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0024_seed_management_company_and_backfill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='we_book',
        ),
        migrations.RemoveField(
            model_name='property',
            name='we_clean',
        ),
    ]
