# Generated by Django 5.2.8 on 2026-08-26

from django.db import migrations

CONTACT_FIELDS = (
    'head_name', 'head_email', 'head_phone',
    'maintenance_name', 'maintenance_phone', 'maintenance_email',
    'liaison_name', 'liaison_phone', 'liaison_email',
    'cleaning_name', 'cleaning_phone', 'cleaning_email',
    'finance_name', 'finance_phone', 'finance_email',
)


def migrate_contacts(apps, schema_editor):
    """Copy every linked Manager row's 15 contact fields directly onto its ManagementCompany
    (via the about-to-be-removed contacts_id link) - folding the two models together per Thomas's
    ask, rather than keeping them as separate cross-referenced rows. Only one pair exists today
    (the seeded "KLT Property Services Lda." company <-> Manager row), but written generically."""
    ManagementCompany = apps.get_model('properties', 'ManagementCompany')
    for company in ManagementCompany.objects.filter(contacts_id__isnull=False).select_related('contacts'):
        manager = company.contacts
        for field in CONTACT_FIELDS:
            setattr(company, field, getattr(manager, field) or '')
        company.save()


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0026_managementcompany_contact_fields'),
    ]

    operations = [
        migrations.RunPython(migrate_contacts, migrations.RunPython.noop),
    ]
