# Generated by Django 5.2.8 on 2026-08-26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0027_migrate_manager_contacts_into_management_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managementcompany',
            name='contacts',
        ),
    ]
