# Generated by Django 5.2.8 on 2026-08-26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0028_remove_managementcompany_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='manager',
        ),
    ]
