# Generated by Django 5.2.8 on 2026-08-26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0029_remove_property_manager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
