# Generated by Django 5.2.8 on 2026-08-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0030_delete_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='color',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
