# Generated by Django 5.2.8 on 2026-08-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0031_location_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementcompany',
            name='check_in_method',
            field=models.CharField(blank=True, choices=[('self_check_in', 'Always self check-in'), ('in_person', 'Always in person'), ('mixed', 'Mixed - depends on arrival time')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='managementcompany',
            name='provides_washing_materials',
            field=models.BooleanField(blank=True, help_text='Whether this company supplies washing-up liquid, soap, and laundry tabs.', null=True),
        ),
        migrations.AddField(
            model_name='managementcompany',
            name='self_check_in_after',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managementcompany',
            name='standard_meet_and_greet_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='managementcompany',
            name='towels_per_guest',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
