# Generated by Django 5.2.8 on 2026-08-27 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0032_managementcompany_check_in_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managementcompany',
            name='provides_washing_materials',
        ),
        migrations.AddField(
            model_name='managementcompany',
            name='freshen_after_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managementcompany',
            name='includes_beach_towels',
            field=models.BooleanField(blank=True, help_text='Whether towels_per_guest includes a beach towel.', null=True),
        ),
        migrations.CreateModel(
            name='WashingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='washing_materials', to='properties.managementcompany')),
            ],
            options={
                'verbose_name': 'Washing Material',
                'verbose_name_plural': 'Washing Materials',
                'db_table': 'management_company_washing_materials',
                'ordering': ('title',),
            },
        ),
    ]
