# Generated by Django 5.2.8 on 2026-08-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0033_remove_managementcompany_provides_washing_materials_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementcompany',
            name='linen_provided',
            field=models.BooleanField(blank=True, help_text="Whether this company dresses beds in linen appropriate to the season - drives the Manage Booking hub's Amenities page (bookings/views.py::BookingManageAmenitiesView), via Property.cleaning_company.", null=True),
        ),
    ]
