# Generated by Django 5.2.8 on 2026-08-28 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0036_seed_platforms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icallink',
            name='ical_source',
        ),
    ]
