# Generated by Django 5.2.8 on 2026-08-28 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0039_backfill_property_platform_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='airbnb_id',
        ),
        migrations.RemoveField(
            model_name='property',
            name='booking_com_id',
        ),
        migrations.RemoveField(
            model_name='property',
            name='vrbo_id',
        ),
    ]
