# Generated by Django 5.2.8 on 2026-08-28 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0040_remove_old_property_platform_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyplatformid',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property_ids', to='properties.platform'),
        ),
    ]
