# Generated by Django 5.2.8 on 2026-08-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0041_protect_property_platform_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementcompany',
            name='checkins_on_calendar',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='managementcompany',
            name='cleans_on_calendar',
            field=models.BooleanField(default=True),
        ),
    ]
