# Generated by Django 5.2.8 on 2026-08-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0042_management_company_calendar_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementcompany',
            name='finances_managed_internally',
            field=models.BooleanField(default=False),
        ),
    ]
