# Generated by Django 5.2.8 on 2026-08-30 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0044_owner_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='icallink',
            name='is_owner_link',
            field=models.BooleanField(default=False),
        ),
    ]
