# Generated by Django 5.2.8 on 2026-09-01 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0045_icallink_is_owner_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementcompany',
            name='bookable_on_website',
            field=models.BooleanField(default=True),
        ),
    ]
