# Generated by Django 5.2.8 on 2026-09-01 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0046_managementcompany_bookable_on_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='icallink',
            name='exclude_summary_contains',
            field=models.TextField(blank=True, default='', help_text="One term per line. A calendar event whose title contains any of these (case-insensitive) is skipped entirely - e.g. 'Not Available' for Airbnb blocks, 'Tentative' for Vrbo enquiries."),
        ),
    ]
