# Generated by Django 6.0.1 on 2026-09-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0047_icallink_exclude_summary_contains'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='parking_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
