# Generated by Django 5.2.8 on 2026-09-03 23:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0048_location_parking_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='commission_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Flat expected commission this platform takes, as a percentage - used to gross up Direct rates for the Rate Card's Platform rates popup. Leave blank if not known yet; that platform's column just won't show a figure.", max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='commission %'),
        ),
    ]
