# Generated by Django 5.2.8 on 2026-09-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0049_platform_commission_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='self_check_in_instructions',
            field=models.TextField(blank=True, default=''),
        ),
    ]
