# Generated by Django 5.2.8 on 2026-09-05 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0050_property_self_check_in_instructions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyAccessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. "Building gate", "Apartment door"', max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_codes', to='properties.property')),
            ],
            options={
                'verbose_name': 'Property Access Code',
                'verbose_name_plural': 'Property Access Codes',
                'db_table': 'property_access_codes',
                'ordering': ['order', 'pk'],
            },
        ),
    ]
