# Generated by Django 5.2.8 on 2026-09-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0051_propertyaccesscode'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='self_check_in_fallback_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='location',
            name='self_check_in_fallback_instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='location',
            name='self_check_in_preferred_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='location',
            name='self_check_in_preferred_instructions',
            field=models.TextField(blank=True, default=''),
        ),
    ]
