# Generated by Django 5.2.8 on 2026-09-06 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0052_location_self_check_in_fallback_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='in_person_check_in_instructions',
            field=models.TextField(blank=True, default=''),
        ),
    ]
