# Generated by Django 5.2.8 on 2026-09-06 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0053_property_in_person_check_in_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementcompany',
            name='late_check_in_after',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managementcompany',
            name='late_check_in_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
