# Generated by Django 6.0.1 on 2026-09-07 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0054_managementcompany_late_check_in_after_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
