# Generated by Django 5.2.8 on 2026-09-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0055_property_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='after_checkout_access_instructions',
            field=models.TextField(blank=True, default=''),
        ),
    ]
