# Generated by Django 5.2.8 on 2026-09-08 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0056_owner_currency_and_field_cleanup'),
        ('properties', '0057_backfill_after_checkout_access_and_mon_t_bbq'),
    ]

    operations = [
    ]
