# Generated by Django 5.2.8 on 2026-09-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0060_owner_secondary_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('pt', 'Português')], default='en', max_length=2),
        ),
    ]
