# Generated by Django 6.0.1 on 2026-09-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0061_owner_preferred_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='bank_account_holder_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='bank_iban',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='revolut_counterparty_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
