# Generated by Django 6.0.1 on 2026-09-12 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0062_owner_bank_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='bank_account_holder_name',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='bank_iban',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='revolut_counterparty_id',
        ),
        migrations.CreateModel(
            name='OwnerBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('EUR', 'Euros'), ('GBP', 'Pounds')], max_length=3)),
                ('account_holder_name', models.CharField(max_length=200)),
                ('iban', models.CharField(blank=True, max_length=34, null=True)),
                ('sort_code', models.CharField(blank=True, max_length=10, null=True)),
                ('account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('revolut_counterparty_id', models.CharField(blank=True, max_length=50, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='properties.owner')),
            ],
            options={
                'verbose_name': 'Owner Bank Account',
                'verbose_name_plural': 'Owner Bank Accounts',
                'db_table': 'property_owner_bank_accounts',
                'ordering': ('currency',),
                'constraints': [models.UniqueConstraint(fields=('owner', 'currency'), name='unique_owner_bank_account_currency')],
            },
        ),
    ]
