# Generated by Django 5.2.8 on 2026-09-12 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0063_owner_bank_account_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerbankaccount',
            name='address_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ownerbankaccount',
            name='address_postcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ownerbankaccount',
            name='address_street',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
