# Generated by Django 5.2.8 on 2026-09-15 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0065_accountant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='extra_adult_rate',
            field=models.DecimalField(decimal_places=2, default=10, help_text="Charge per night for each adult beyond the property's free allowance (2 guests per bedroom).", max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='extra adult'),
        ),
        migrations.AlterField(
            model_name='price',
            name='extra_child_rate',
            field=models.DecimalField(decimal_places=2, default=5, help_text="Charge per night for each child beyond the property's free allowance (2 guests per bedroom). Adults fill the free places first, so it's the children who spill over that are charged.", max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='extra child'),
        ),
    ]
