# Generated by Django 5.2.8 on 2026-08-24 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='id_card',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='nif_number',
        ),
    ]
