# Generated by Django 5.2.8 on 2026-08-29 21:25

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_remove_guest_id_card_remove_guest_nationality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
