"""
Django settings for klt_web project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from env_settings import (
    DJANGO_SECRET_KEY,
    DATABASE_NAME,
    DATABASE_USER,
    DATABASE_PASSWORD,
    DATABASE_HOST,
    DATABASE_PORT,
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = DJANGO_SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django_countries',
    'index.apps.IndexConfig',
    'properties.apps.PropertiesConfig',
    'availability.apps.AvailabilityConfig',
    'bookings.apps.BookingsConfig',
    'guests.apps.GuestsConfig',
    'staff.apps.StaffConfig',
    'finance.apps.FinanceConfig',
    'owners.apps.OwnersConfig',
    'communications.apps.CommunicationsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'klt_web.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'staff.context_processors.staff_nav_permissions',
            ],
        },
    },
]

WSGI_APPLICATION = 'klt_web.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': DATABASE_NAME,
        'USER': DATABASE_USER,
        'PASSWORD': DATABASE_PASSWORD,
        'HOST': DATABASE_HOST,
        'PORT': DATABASE_PORT,
        # Django's own default (0) closes and reopens the DB connection on every single request -
        # fine for a local socket, expensive for this remote Railway proxy: measured at ~0.4s just
        # to open a fresh connection, on top of query time, so every page load/navigation on this
        # dev server was paying that twice (once for the request, again next time) for no reason -
        # nothing here needs a *fresh* connection each request, just a live one. 60s lets
        # runserver's process reuse one connection across requests within that window instead
        # (2026-09-03, found while diagnosing slow cleaning-calendar loads/navigation).
        'CONN_MAX_AGE': 60,
    }
}

# Opt-in override for `manage.py test`: the real DB above is the shared remote Railway Postgres,
# which has consistently slow/variable round-trip latency (see project memory) - a full test run
# there can take 20-25+ minutes even though the test DB itself is tiny (Django's TestCase builds
# its own fixtures per test and rolls them back, so there's no real data to speed up, only network
# round trips to cut). Set LOCAL_TEST_DB=1 to point at a local Postgres instead - HOST/PORT blank
# makes psycopg connect over the local Unix socket with peer auth (no password needed, matches
# `psql -U thomas-bogg -d postgres` already working passwordless on this machine). Only ever
# swaps the connection when this env var is explicitly set - every other run (including a plain
# `manage.py test` with nothing set) still uses the real remote DB, so this can never silently
# affect a non-test command. django-admin's own test runner creates/destroys a `test_<NAME>` DB
# on whichever server DATABASES points at, so this is the only override needed - it doesn't
# matter that the existing local `kltwebdb` database itself is stale/unmigrated.
if os.environ.get('LOCAL_TEST_DB'):
    DATABASES['default'].update({
        'NAME': 'kltwebdb',
        'USER': 'thomas-bogg',
        'PASSWORD': '',
        'HOST': '',
        'PORT': '',
    })


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'GMT'

USE_I18N = True

USE_TZ = True

# Overrides en-us's m/d/Y default with EU-style d-m-Y - see klt_web/formats/en/formats.py
FORMAT_MODULE_PATH = 'klt_web.formats'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    "static/",
]

# Media files (user-uploaded content)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
