# Generated by Django 5.2.8 on 2026-03-08 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pims_id', models.IntegerField(blank=True, null=True)),
                ('platform_id', models.CharField(blank=True, max_length=200, null=True)),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('is_owner', models.BooleanField()),
                ('enquiry_status', models.CharField(max_length=100)),
                ('enquiry_date', models.DateField(blank=True, null=True)),
                ('enquiry_source', models.CharField(max_length=100)),
                ('adults', models.IntegerField()),
                ('children', models.IntegerField()),
                ('babies', models.IntegerField()),
                ('manual_guests', models.BooleanField()),
                ('last_updated', models.DateTimeField()),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='guests.guest')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='properties.property')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'db_table': 'bookings',
            },
        ),
        migrations.CreateModel(
            name='Arrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(blank=True, max_length=50, null=True)),
                ('is_faro', models.BooleanField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('self_check_in', models.BooleanField(blank=True, null=True)),
                ('meet_greet', models.BooleanField()),
                ('manual_date', models.BooleanField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arrival', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Arrival',
                'verbose_name_plural': 'Arrivals',
                'db_table': 'booking_arrivals',
            },
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_transfer', models.BooleanField(blank=True, null=True)),
                ('credit_card', models.BooleanField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('basic_rental', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('admin', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('security', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('security_method', models.CharField(blank=True, max_length=100, null=True)),
                ('platform_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('extra_nights', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('manual_charges', models.BooleanField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Charge',
                'verbose_name_plural': 'Charges',
                'db_table': 'booking_charges',
            },
        ),
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(blank=True, max_length=50, null=True)),
                ('is_faro', models.BooleanField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('clean', models.BooleanField()),
                ('manual_date', models.BooleanField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='departure', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Departure',
                'verbose_name_plural': 'Departures',
                'db_table': 'booking_departures',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_payment', models.BooleanField(blank=True, null=True)),
                ('arrival_questionnaire', models.BooleanField(blank=True, null=True)),
                ('security_deposit_request', models.BooleanField(blank=True, null=True)),
                ('arrival_information', models.BooleanField(blank=True, null=True)),
                ('guest_registration_form', models.BooleanField(blank=True, null=True)),
                ('check_in_instructions', models.BooleanField(blank=True, null=True)),
                ('final_days_reminder', models.BooleanField(blank=True, null=True)),
                ('goodbye', models.BooleanField(blank=True, null=True)),
                ('management', models.BooleanField(blank=True, null=True)),
                ('pay_owner', models.BooleanField(blank=True, null=True)),
                ('security_deposit_return', models.BooleanField(blank=True, null=True)),
                ('airport_transfers', models.BooleanField(blank=True, null=True)),
                ('guest_registration_form_to_owner', models.BooleanField(blank=True, null=True)),
                ('paused', models.BooleanField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Booking Email',
                'verbose_name_plural': 'Booking Emails',
                'db_table': 'booking_emails',
            },
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cot', models.BooleanField(blank=True, null=True)),
                ('high_chair', models.BooleanField(blank=True, null=True)),
                ('welcome_pack', models.BooleanField(blank=True, null=True)),
                ('welcome_pack_modifications', models.TextField(blank=True, null=True)),
                ('mid_stay_clean', models.BooleanField(blank=True, null=True)),
                ('late_checkout', models.BooleanField(blank=True, null=True)),
                ('other_requests', models.TextField(blank=True, null=True)),
                ('extra_nights', models.BooleanField(blank=True, null=True)),
                ('airport_transfers', models.BooleanField(blank=True, null=True)),
                ('airport_transfer_inbound_only', models.BooleanField(blank=True, null=True)),
                ('airport_transfer_outbound_only', models.BooleanField(blank=True, null=True)),
                ('child_seats', models.CharField(blank=True, max_length=200, null=True)),
                ('excess_baggage', models.CharField(blank=True, max_length=200, null=True)),
                ('owner_is_paying', models.BooleanField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Extra',
                'verbose_name_plural': 'Extras',
                'db_table': 'booking_extras',
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_payment', models.CharField(blank=True, max_length=200, null=True)),
                ('arrival_questionnaire', models.CharField(blank=True, max_length=200, null=True)),
                ('guest_registration', models.CharField(blank=True, max_length=200, null=True)),
                ('guest_registration_done', models.BooleanField(blank=True, null=True)),
                ('security_deposit', models.CharField(blank=True, max_length=200, null=True)),
                ('pims_uin', models.CharField(blank=True, max_length=200, null=True)),
                ('pims_oid', models.CharField(blank=True, max_length=200, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Booking Form',
                'verbose_name_plural': 'Booking Forms',
                'db_table': 'booking_forms',
            },
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('details', models.TextField(blank=True, null=True)),
                ('extras', models.TextField(blank=True, null=True)),
                ('email_sent', models.BooleanField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Booking Update',
                'verbose_name_plural': 'Booking Updates',
                'db_table': 'booking_updates',
            },
        ),
    ]
