# Generated by Django 5.2.8 on 2026-08-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrival',
            name='manual_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='manual_guests',
        ),
        migrations.AddField(
            model_name='booking',
            name='ical_uid',
            field=models.URLField(blank=True, null=True),
        ),
    ]
