# Generated by Django 6.0.1 on 2026-08-17 16:55

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_arrival_manual_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_fee_percent', models.DecimalField(decimal_places=2, default=Decimal('5.50'), help_text='Admin fee charged cumulatively on top of the basic rental, as a percentage.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('deposit_percent_at_booking', models.DecimalField(decimal_places=2, default=Decimal('25.00'), help_text='Percentage of the rental + admin fee due at the reservation stage. The remainder is due at the balance payment stage.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('balance_due_days_before_arrival', models.PositiveIntegerField(default=56, help_text='How many days before arrival the balance payment becomes due.')),
                ('security_deposit_amount', models.DecimalField(decimal_places=2, default=Decimal('200.00'), help_text='Fixed refundable security deposit. Collected in cash at check-in, separate from the online rental/admin payment split.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
            ],
            options={
                'verbose_name': 'Booking Settings',
                'verbose_name_plural': 'Booking Settings',
                'db_table': 'booking_settings',
            },
        ),
    ]
