# Generated by Django 6.0.1 on 2026-08-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_bookingsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsettings',
            name='monthly_discount_min_nights',
            field=models.PositiveIntegerField(default=28, help_text="Minimum number of nights a stay must be for a property's monthly discount to apply."),
        ),
    ]
