# Generated by Django 6.0.1 on 2026-08-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_bookingsettings_monthly_discount_min_nights'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reference',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='charge',
            name='balance_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charge',
            name='due_at_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='charge',
            name='due_at_booking',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
