# Generated by Django 6.0.1 on 2026-08-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_reference_charge_balance_due_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Booking Condition',
                'verbose_name_plural': 'Booking Conditions',
                'db_table': 'booking_conditions',
                'ordering': ('order',),
            },
        ),
    ]
