# Generated by Django 6.0.1 on 2026-08-17 22:53

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_bookingcondition'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsettings',
            name='gbp_conversion_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.8600'), help_text='Euro-to-Pound rate for optional GBP price quotes (amount in GBP = amount in EUR × this rate). Charges are always recorded in EUR regardless of the quote currency shown to the guest.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
