# Generated by Django 6.0.1 on 2026-08-17 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_bookingsettings_gbp_conversion_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='gbp_conversion_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
    ]
