# Generated by Django 6.0.1 on 2026-08-17 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_charge_gbp_conversion_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='currency',
            field=models.CharField(blank=True, choices=[('EUR', 'EUR'), ('GBP', 'GBP')], max_length=3, null=True),
        ),
    ]
