# Generated by Django 5.2.8 on 2026-08-18 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_alter_charge_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='hold_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingsettings',
            name='revolut_hold_extension_minutes',
            field=models.PositiveIntegerField(default=20, help_text='Extra minutes granted when Revolut reports a payment in progress (e.g. mid Open Banking bank-app confirmation), instead of releasing the hold.'),
        ),
        migrations.AddField(
            model_name='bookingsettings',
            name='revolut_hold_minutes',
            field=models.PositiveIntegerField(default=20, help_text='Minutes a Revolut-path deposit hold lasts with no payment signal at all before being released.'),
        ),
        migrations.AddField(
            model_name='bookingsettings',
            name='wise_hold_hours',
            field=models.PositiveIntegerField(default=12, help_text='Hours a Wise-path deposit hold lasts. Flat, since Wise gives no in-progress payment signal to extend on.'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('revolut', 'Revolut'), ('wise', 'Wise')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('paid', 'Paid'), ('declined', 'Declined'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('revolut_order_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('revolut_checkout_url', models.URLField(blank=True, null=True)),
                ('last_event_type', models.CharField(blank=True, max_length=100, null=True)),
                ('in_progress_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'booking_payments',
            },
        ),
    ]
