# Generated by Django 5.2.8 on 2026-08-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_booking_hold_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsettings',
            name='extend_wise_hold_on_weekends',
            field=models.BooleanField(default=True, help_text="If a Wise-path reservation is made on a Friday or Saturday, hold for a number of business days instead of the flat hour window - bank transfers often don't clear over the weekend."),
        ),
        migrations.AddField(
            model_name='bookingsettings',
            name='wise_weekend_hold_business_days',
            field=models.PositiveIntegerField(default=2, help_text='Business days (Mon-Fri) to hold for when extend_wise_hold_on_weekends applies. Only used for reservations made on a Friday or Saturday.'),
        ),
    ]
