# Generated by Django 5.2.8 on 2026-08-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_bookingsettings_extend_wise_hold_on_weekends_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingsettings',
            name='extend_wise_hold_on_weekends',
        ),
        migrations.RemoveField(
            model_name='bookingsettings',
            name='wise_hold_hours',
        ),
        migrations.RemoveField(
            model_name='bookingsettings',
            name='wise_weekend_hold_business_days',
        ),
        migrations.AddField(
            model_name='bookingsettings',
            name='payment_clearing_business_days',
            field=models.PositiveIntegerField(default=3, help_text="Business days (Mon-Fri) a deposit hold lasts once a payment is confirmed to be clearing: for Wise, from the moment the reservation is made (Wise gives no in-progress signal to extend on); for Revolut, from the moment Revolut reports ORDER_PAYMENT_AUTHENTICATED (the guest approved payment at their own bank - card payments settle in seconds after this so the long window costs them nothing, but Open Banking bank transfers can take up to 2 business days to clear, and Revolut doesn't tell us which one a guest used)."),
        ),
    ]
