# Generated by Django 5.2.8 on 2026-08-19 16:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_remove_bookingsettings_extend_wise_hold_on_weekends_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsettings',
            name='adult_min_age',
            field=models.PositiveIntegerField(default=13, help_text='Age at time of stay (inclusive) from which a guest is priced as an adult.'),
        ),
        migrations.AddField(
            model_name='bookingsettings',
            name='child_min_age',
            field=models.PositiveIntegerField(default=2, help_text='Age at time of stay (inclusive) from which a guest is priced as a child rather than an infant. Below this: infant, currently free (see cot-as-extra, not yet built).'),
        ),
        migrations.CreateModel(
            name='BookingGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(120)])),
                ('is_lead', models.BooleanField(default=False)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Booking Guest',
                'verbose_name_plural': 'Booking Guests',
                'db_table': 'booking_guests',
                'ordering': ('-is_lead', 'id'),
            },
        ),
    ]
