# Generated by Django 5.2.8 on 2026-08-19 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_bookingsettings_adult_min_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Total the guest paid the platform.', max_digits=10, null=True)),
                ('platform_commission', models.DecimalField(blank=True, decimal_places=2, help_text='What the platform kept as its fee/commission.', max_digits=10, null=True)),
                ('payout_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Net amount actually paid out to us.', max_digits=10, null=True)),
                ('payout_currency', models.CharField(blank=True, choices=[('EUR', 'EUR'), ('GBP', 'GBP')], max_length=3, null=True)),
                ('payout_date', models.DateField(blank=True, help_text="When the platform's payout was received, if known.", null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='platform_payout', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Platform Payout',
                'verbose_name_plural': 'Platform Payouts',
                'db_table': 'booking_platform_payouts',
            },
        ),
    ]
