# Generated by Django 5.2.8 on 2026-08-20 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_platformpayout'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('default_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Request type',
                'db_table': 'booking_request_types',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='WelcomePackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Welcome pack item',
                'db_table': 'welcome_pack_items',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.RemoveField(
            model_name='extra',
            name='other_requests',
        ),
        migrations.AddField(
            model_name='extra',
            name='welcome_pack_charge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Staff-entered charge if the guest's welcome pack customisation isn't a free like-for-like swap.", max_digits=8, null=True),
        ),
        migrations.CreateModel(
            name='BookingRequestedExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('price_at_request', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_extras', to='bookings.booking')),
                ('request_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookings.requesttype')),
            ],
            options={
                'db_table': 'booking_requested_extras',
                'ordering': ('created_at',),
            },
        ),
    ]
