# Generated by Django 5.2.8 on 2026-08-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_requesttype_welcomepackitem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='welcomepackitem',
            options={'ordering': ('category', 'order', 'name'), 'verbose_name': 'Welcome pack item'},
        ),
        migrations.RemoveField(
            model_name='extra',
            name='welcome_pack_modifications',
        ),
        migrations.AddField(
            model_name='extra',
            name='welcome_pack_drinks',
            field=models.CharField(blank=True, choices=[('alcoholic', 'Alcoholic'), ('non_alcoholic', 'Non-alcoholic')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='extra',
            name='welcome_pack_food',
            field=models.CharField(blank=True, choices=[('standard', 'Standard'), ('vegan', 'Vegan')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='extra',
            name='welcome_pack_note',
            field=models.TextField(blank=True, help_text="Allergies or dietary notes only - the pack's contents are fixed by the food/drinks choice, not open to swap requests.", null=True),
        ),
        migrations.AddField(
            model_name='welcomepackitem',
            name='category',
            field=models.CharField(choices=[('food_standard', 'Food - standard only'), ('food_vegan', 'Food - vegan only'), ('food_common', 'Food - both standard and vegan'), ('drinks_alcoholic', 'Drinks - alcoholic only'), ('drinks_non_alcoholic', 'Drinks - non-alcoholic only'), ('drinks_common', 'Drinks - both alcoholic and non-alcoholic')], default='food_common', max_length=24),
        ),
        migrations.AlterField(
            model_name='extra',
            name='welcome_pack_charge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Staff-entered charge for a rare exception granted outside the standard fixed pack choices.', max_digits=8, null=True),
        ),
    ]
