# Generated by Django 5.2.8 on 2026-08-20 15:26

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_alter_welcomepackitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirportTransferPriceBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_guests', models.PositiveIntegerField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'verbose_name': 'Airport transfer price band',
                'db_table': 'airport_transfer_price_bands',
                'ordering': ('max_guests',),
            },
        ),
        migrations.CreateModel(
            name='ExtrasSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_transfer_night_surcharge', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('airport_transfer_night_window_start', models.TimeField(default=datetime.time(22, 0))),
                ('airport_transfer_night_window_end', models.TimeField(default=datetime.time(6, 0))),
            ],
            options={
                'verbose_name': 'Extras Settings',
                'verbose_name_plural': 'Extras Settings',
                'db_table': 'extras_settings',
            },
        ),
        migrations.RemoveField(
            model_name='extra',
            name='airport_transfer_inbound_only',
        ),
        migrations.RemoveField(
            model_name='extra',
            name='airport_transfer_outbound_only',
        ),
        migrations.RemoveField(
            model_name='extra',
            name='airport_transfers',
        ),
        migrations.RemoveField(
            model_name='extra',
            name='child_seats',
        ),
        migrations.RemoveField(
            model_name='extra',
            name='excess_baggage',
        ),
        migrations.CreateModel(
            name='AirportTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('inbound', 'Inbound (arrival)'), ('outbound', 'Outbound (departure)')], max_length=10)),
                ('is_faro', models.BooleanField(default=True, help_text='Uncheck if flying via an airport other than Faro.')),
                ('flight_number', models.CharField(blank=True, max_length=20)),
                ('time', models.TimeField()),
                ('adults', models.PositiveIntegerField(default=1)),
                ('children', models.PositiveIntegerField(default=0)),
                ('infants', models.PositiveIntegerField(default=0)),
                ('child_seats', models.CharField(blank=True, max_length=200)),
                ('excess_baggage', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('price_at_request', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airport_transfers', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Airport transfer',
                'db_table': 'airport_transfers',
                'ordering': ('created_at',),
            },
        ),
    ]
