# Generated by Django 5.2.8 on 2026-08-20 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_airporttransferpriceband_extrassettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='manual_override',
            field=models.BooleanField(default=False, help_text='Set automatically when staff record an extra-nights date adjustment (see BookingDateAdjustment). The external platform-sync scraper must check this before touching arrival_date/departure_date on this booking - true means the dates were adjusted directly with the guest and the scraper must not overwrite them.'),
        ),
        migrations.CreateModel(
            name='BookingDateAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_arrival_date', models.DateField(editable=False)),
                ('previous_departure_date', models.DateField(editable=False)),
                ('new_arrival_date', models.DateField()),
                ('new_departure_date', models.DateField()),
                ('additional_charge', models.DecimalField(decimal_places=2, default=0, help_text='Cash difference the guest pays on arrival - not part of Charge.', max_digits=8)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_adjustments', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Booking date adjustment',
                'db_table': 'booking_date_adjustments',
                'ordering': ('created_at',),
            },
        ),
    ]
