# Generated by Django 5.2.8 on 2026-08-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0018_booking_manual_override_bookingdateadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra',
            name='cot_high_chair_charge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Combined price for whichever of cot/high chair were requested, computed from ExtrasSettings at request time (day-tier pricing plus the combo discount if both were requested) - see ExtrasSettings.compute_cot_high_chair_price().', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='extrassettings',
            name='cot_and_high_chair_combo_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Flat discount subtracted from the combined price when both a cot and a high chair are requested together on the same booking.', max_digits=8),
        ),
        migrations.AddField(
            model_name='extrassettings',
            name='cot_price_long_stay',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Flat price for a stay of more than 7 nights.', max_digits=8),
        ),
        migrations.AddField(
            model_name='extrassettings',
            name='cot_price_short_stay',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Flat price for a stay of up to 7 nights.', max_digits=8),
        ),
        migrations.AddField(
            model_name='extrassettings',
            name='high_chair_price_long_stay',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Flat price for a stay of more than 7 nights.', max_digits=8),
        ),
        migrations.AddField(
            model_name='extrassettings',
            name='high_chair_price_short_stay',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Flat price for a stay of up to 7 nights.', max_digits=8),
        ),
    ]
