# Generated by Django 5.2.8 on 2026-08-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0019_extra_cot_high_chair_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra',
            name='late_checkout_charge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Flat fee snapshotted from ExtrasSettings.late_checkout_price at request time.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='extra',
            name='late_checkout_time',
            field=models.TimeField(blank=True, help_text="Guest's exact requested checkout time. A future cleaning-automation system may add a 'latest possible' boundary this has to respect - not yet built.", null=True),
        ),
        migrations.AddField(
            model_name='extrassettings',
            name='late_checkout_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Flat fee for a late checkout request. A future cleaning-automation system may vary this by how late the checkout is - kept as a single flat fee for now.', max_digits=8),
        ),
    ]
