# Generated by Django 5.2.8 on 2026-08-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0020_extra_late_checkout_charge_extra_late_checkout_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrassettings',
            name='welcome_pack_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Flat price for the standard Welcome Pack (the fixed food/drinks picker). Staff can hand-edit Extra.welcome_pack_charge afterward for a rare exception.', max_digits=8),
        ),
        migrations.AlterField(
            model_name='extra',
            name='welcome_pack_charge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Snapshotted from ExtrasSettings.welcome_pack_price at request time (same convention as every other Extras price field) - staff can hand-edit here afterward for a rare exception outside the standard fixed pack choices.', max_digits=8, null=True),
        ),
    ]
