# Generated by Django 5.2.8 on 2026-08-20 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0021_extrassettings_welcome_pack_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsettings',
            name='balance_reminder_days_before_arrival',
            field=models.PositiveIntegerField(default=63, help_text='How many days before arrival a balance-payment reminder becomes due for staff follow-up (surfaced in the Balance Payments admin, not sent automatically yet). Should be greater than balance_due_days_before_arrival so the guest gets some notice before the balance is actually due - the gap between the two is that notice period.'),
        ),
        migrations.CreateModel(
            name='BalancePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('revolut', 'Revolut'), ('wise', 'Wise')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('paid', 'Paid'), ('declined', 'Declined'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('revolut_order_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('revolut_checkout_url', models.URLField(blank=True, null=True)),
                ('last_event_type', models.CharField(blank=True, max_length=100, null=True)),
                ('in_progress_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance_payment', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Balance Payment',
                'verbose_name_plural': 'Balance Payments',
                'db_table': 'booking_balance_payments',
            },
        ),
    ]
