# Generated by Django 5.2.8 on 2026-08-21 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0022_bookingsettings_balance_reminder_days_before_arrival_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsettings',
            name='extras_edit_cutoff_days_before_arrival',
            field=models.PositiveIntegerField(default=3, help_text='How many days before arrival Extras (Welcome Pack, Cot/High Chair, Late Checkout, Airport Transfers, special requests) can still be edited self-serve via the Manage Booking hub.'),
        ),
        migrations.CreateModel(
            name='GuestListAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_party_size', models.PositiveIntegerField(editable=False)),
                ('new_party_size', models.PositiveIntegerField(editable=False)),
                ('additional_charge', models.DecimalField(decimal_places=2, default=0, help_text='Extra rental+admin cost of the added guest(s) - cash at check-in, not part of Charge.', max_digits=8)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_list_adjustments', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Guest list adjustment',
                'db_table': 'booking_guest_list_adjustments',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddField(
            model_name='bookingguest',
            name='added_via_adjustment',
            field=models.ForeignKey(blank=True, help_text='Set only when this row was added post-payment via the Manage Booking hub. Null for every guest present at the original deposit/balance stage.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_guests', to='bookings.guestlistadjustment'),
        ),
    ]
