# Generated by Django 5.2.8 on 2026-08-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0023_bookingsettings_extras_edit_cutoff_days_before_arrival_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departure',
            name='clean',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='departure',
            name='manual_date',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
