# Generated by Django 5.2.8 on 2026-08-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0024_alter_departure_clean_alter_departure_manual_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrival',
            name='is_faro',
        ),
        migrations.RemoveField(
            model_name='departure',
            name='is_faro',
        ),
        migrations.AddField(
            model_name='arrival',
            name='method',
            field=models.CharField(choices=[('flight_faro', 'Flight to Faro'), ('flight_lisbon', 'Flight to Lisbon'), ('bus', 'Bus to Albufeira'), ('train', 'Train to Ferreiras (Albufeira)'), ('driving', 'Driving from another location'), ('other', 'Other')], default='flight_faro', max_length=20),
        ),
        migrations.AddField(
            model_name='arrival',
            name='travelling_from',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='departure',
            name='method',
            field=models.CharField(choices=[('flight_faro', 'Flight to Faro'), ('flight_lisbon', 'Flight to Lisbon'), ('bus', 'Bus to Albufeira'), ('train', 'Train to Ferreiras (Albufeira)'), ('driving', 'Driving from another location'), ('other', 'Other')], default='flight_faro', max_length=20),
        ),
        migrations.AddField(
            model_name='departure',
            name='travelling_from',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
