# Generated by Django 5.2.8 on 2026-08-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0025_remove_arrival_is_faro_remove_departure_is_faro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrival',
            name='hiring_car',
            field=models.BooleanField(default=False),
        ),
    ]
