# Generated by Django 5.2.8 on 2026-08-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0026_arrival_hiring_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='ical_uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
