# Generated by Django 5.2.8 on 2026-08-23 15:29

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0027_alter_booking_ical_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high_season_commission_percent', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text="Default management commission on rental income during high season. The legacy system also varied this by an owner-level 'wants accounting' flag and a VAT-regime cutoff date - deliberately simplified to season only for now.", max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('low_season_commission_percent', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Default management commission on rental income outside high season.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('high_season_start_month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=4, help_text='First month of high season (inclusive).')),
                ('high_season_end_month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=10, help_text='Last month of high season (inclusive).')),
                ('klt_commission_share_percent', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Share of the commission above kept by KLT itself, with the remainder going to the other party in the historical split arrangement (the legacy system phases this to 100% for any booking arriving after 2026 - kept configurable in case that arrangement changes again).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('vat_rate_percent', models.DecimalField(decimal_places=2, default=Decimal('23.00'), help_text='Portuguese VAT/IVA rate applied to invoiced commission and platform fees.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('cleaning_surcharge_one_bedroom', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text="Added on top of a property's own standard cleaning fee for a 1-bedroom property.", max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('cleaning_surcharge_multi_bedroom', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text="Added on top of a property's own standard cleaning fee for a property with more than 1 bedroom.", max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('cleaning_high_occupancy_surcharge', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text="Added on top of the cleaning fee when a stay's guest count exceeds 2 per bedroom (the legacy system's trigger rule - not yet automatically applied here).", max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('meet_greet_fee', models.DecimalField(decimal_places=2, default=Decimal('28.00'), help_text='Flat fee for a meet & greet (see Owner.default_meet_greet for whether one applies by default).', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('extra_bed_fee', models.DecimalField(decimal_places=2, default=Decimal('25.00'), help_text='Flat fee for an extra bed. In the legacy system this only ever triggered for one specific property - stored here as a general default, not yet tied to any automatic per-property trigger.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
            ],
            options={
                'verbose_name': 'Payment Settings',
                'verbose_name_plural': 'Payment Settings',
                'db_table': 'payment_settings',
            },
        ),
    ]
