# Generated by Django 5.2.8 on 2026-08-23 14:45

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0027_alter_booking_ical_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_owner_payout_percent', models.DecimalField(decimal_places=2, default=Decimal('80.00'), help_text='Default share of rental income paid to the owner, before any per-owner override.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('default_rental_commission_percent', models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Default management commission on rental income.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('default_cleaning_commission_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Default management commission on cleaning fees, separate from the rental commission above.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
            ],
            options={
                'verbose_name': 'Payment Settings',
                'verbose_name_plural': 'Payment Settings',
                'db_table': 'payment_settings',
            },
        ),
    ]
