# Generated by Django 5.2.8 on 2026-08-23 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0028_paymentsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='welcomepackitem',
            options={'ordering': ('category', 'name'), 'verbose_name': 'Welcome pack item'},
        ),
        migrations.RemoveField(
            model_name='welcomepackitem',
            name='order',
        ),
    ]
