# Generated by Django 5.2.8 on 2026-08-23 16:27

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0029_alter_welcomepackitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrassettings',
            name='cot_and_high_chair_combo_discount',
        ),
        migrations.AddField(
            model_name='extrassettings',
            name='cot_and_high_chair_combo_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage discount applied to the combined price when both a cot and a high chair are requested together on the same booking.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
    ]
