# Generated by Django 5.2.8 on 2026-08-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0030_remove_extrassettings_cot_and_high_chair_combo_discount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AirportTransferPriceBand',
        ),
        migrations.AddField(
            model_name='extrassettings',
            name='airport_transfer_price_1_4_guests',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Flat price for a transfer carrying 1 to 4 guests total (adults + children + infants).', max_digits=8),
        ),
        migrations.AddField(
            model_name='extrassettings',
            name='airport_transfer_price_5_8_guests',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Flat price for a transfer carrying 5 to 8 guests total. More than 8 guests needs a separate transfer booked at one of these two prices, rather than a third tier - in practice there's never been a need for one.", max_digits=8),
        ),
    ]
