# Generated by Django 5.2.8 on 2026-08-24 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0032_faq'),
        ('properties', '0021_amenity_bath_towels_per_guest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='location',
            field=models.ForeignKey(blank=True, help_text="Leave blank to show this on every location's FAQ page.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='properties.location'),
        ),
    ]
