# Generated by Django 5.2.8 on 2026-08-24 21:56

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0033_faq_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('place_of_birth', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('nationality', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('country_of_residence', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('id_type', models.CharField(blank=True, choices=[('id_card', 'ID card'), ('passport', 'Passport')], max_length=10)),
                ('id_number', models.CharField(blank=True, max_length=50)),
                ('issued_by', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('booking_guest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration', to='bookings.bookingguest')),
            ],
            options={
                'verbose_name': 'Guest Registration',
                'verbose_name_plural': 'Guest Registrations',
                'db_table': 'guest_registrations',
            },
        ),
    ]
