# Generated by Django 5.2.8 on 2026-08-24 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0034_guestregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestregistration',
            name='has_nif',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guestregistration',
            name='nif_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
