# Generated by Django 5.2.8 on 2026-08-25 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0035_guestregistration_has_nif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsettings',
            name='charge_vat_on_low_season_direct_commission',
            field=models.BooleanField(default=False, help_text='Whether Internal Commission carries VAT for a direct booking outside high season. High-season commission always carries VAT regardless of origin - this only controls the low-season direct case, which can be disregarded for simplicity.'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='charge_vat_on_low_season_platform_commission',
            field=models.BooleanField(default=True, help_text="Whether Internal Commission carries VAT for a platform booking outside high season. High-season commission always carries VAT regardless of origin, and a platform booking already carries VAT on the platform's own fee year-round - defaults on for consistency, but kept togglable separately from the direct case."),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='regular_payout_days_after_arrival',
            field=models.PositiveIntegerField(default=3, help_text='For an owner paid on a regular schedule (Owner.is_paid_regularly), how many days after guest arrival their payout is due. An owner not on a regular schedule is instead batched into a single payout at the end of the arrival month.'),
        ),
    ]
