# Generated by Django 5.2.8 on 2026-08-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0036_paymentsettings_vat_and_payout_timing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='discount_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='charge',
            name='extra_guest_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
