# Generated by Django 5.2.8 on 2026-08-25 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0037_charge_discount_total_and_extra_guest_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departure',
            name='manual_date',
        ),
    ]
