# Generated by Django 5.2.8 on 2026-08-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0038_remove_departure_manual_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra',
            name='mid_stay_clean_date',
            field=models.DateField(blank=True, help_text="When the mid-stay clean happens - staff-set from the booking detail page's Booking Info panel (mid_stay_clean itself predates any code path that reads or writes it; this field and that UI are what activate it). Feeds staff.utils.sync_cleaning_tasks_for_booking() to create a CleaningTask.", null=True),
        ),
    ]
