# Generated by Django 5.2.8 on 2026-08-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0039_extra_mid_stay_clean_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra',
            name='mid_stay_clean_charge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Snapshotted from ExtrasSettings.compute_mid_stay_clean_price() at request time (same convention as every other Extras price field) - priced by the property's bedroom count, not stay length.", max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='extrassettings',
            name='mid_stay_clean_price_multi_bedroom',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Flat price for a mid-stay clean on a property with more than 1 bedroom.', max_digits=8),
        ),
        migrations.AddField(
            model_name='extrassettings',
            name='mid_stay_clean_price_one_bedroom',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Flat price for a mid-stay clean on a 1-bedroom property. Same one-bedroom/multi-bedroom split as PaymentSettings.cleaning_surcharge_one_bedroom - a different, guest-facing fee though, not the owner-side cleaning surcharge.', max_digits=8),
        ),
        migrations.AlterField(
            model_name='extra',
            name='mid_stay_clean_date',
            field=models.DateField(blank=True, help_text="When the mid-stay clean happens - guest-selectable from the Extras section (BookingFormMixin._save_extras(), same cash-at-check-in convention as every other Extra), or staff-set from the booking detail page's Booking Info panel. Feeds staff.utils.sync_cleaning_tasks_for_booking() to create a CleaningTask.", null=True),
        ),
    ]
