# Generated by Django 5.2.8 on 2026-08-26 16:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0040_extra_mid_stay_clean_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrassettings',
            name='mid_stay_clean_minimum_nights',
            field=models.IntegerField(default=2, help_text="Mid-stay clean isn't offered on a shorter stay than this. 2 is the structural floor - a 1-night stay has no day strictly between arrival and departure at all (see bookings/views.py::BookingFormMixin._extras_context's show_mid_stay_clean and _parse_mid_stay_clean, which both enforce this, not just the display gate).", validators=[django.core.validators.MinValueValidator(2)]),
        ),
    ]
