# Generated by Django 5.2.8 on 2026-08-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0041_extrassettings_mid_stay_clean_minimum_nights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='mid_stay_clean_date',
            field=models.DateField(blank=True, help_text="When the mid-stay clean happens - not guest-editable (auto-set to the middle of the stay by BookingFormMixin._mid_stay_clean_default_date() whenever the guest ticks the Extras-section checkbox, same cash-at-check-in convention as every other Extra), though staff can still hand-set it from the booking detail page's Booking Info panel. Feeds staff.utils.sync_cleaning_tasks_for_booking() to create a CleaningTask - a further nudge within the stay is then a staff-side drag on the cleaning calendar, not a guest choice.", null=True),
        ),
    ]
