# Generated by Django 5.2.8 on 2026-08-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0042_alter_extra_mid_stay_clean_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departure',
            name='clean',
            field=models.BooleanField(default=True),
        ),
    ]
