# Generated by Django 5.2.8 on 2026-08-27 22:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0043_alter_departure_clean'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckinSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faro_buffer_minutes', models.PositiveSmallIntegerField(default=90)),
                ('lisbon_buffer_minutes', models.PositiveSmallIntegerField(default=270)),
                ('transit_buffer_minutes', models.PositiveSmallIntegerField(default=30)),
                ('key_box_prep_time', models.TimeField(default=datetime.time(10, 0))),
                ('welcome_visit_time', models.TimeField(default=datetime.time(10, 0))),
            ],
            options={
                'verbose_name': 'Check-in Settings',
                'verbose_name_plural': 'Check-in Settings',
                'db_table': 'checkin_settings',
            },
        ),
    ]
