# Generated by Django 5.2.8 on 2026-08-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0044_checkinsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrival',
            name='meet_greet',
            field=models.BooleanField(default=True),
        ),
    ]
