# Generated by Django 5.2.8 on 2026-08-29 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0045_alter_arrival_meet_greet'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositBankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=200)),
                ('account_name', models.CharField(blank=True, max_length=200)),
                ('account_number', models.CharField(blank=True, max_length=100)),
                ('sort_code', models.CharField(blank=True, max_length=50)),
                ('iban', models.CharField(blank=True, max_length=50)),
                ('swift_code', models.CharField(blank=True, max_length=50)),
                ('bank_address', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_bank_details', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Deposit Bank Details',
                'verbose_name_plural': 'Deposit Bank Details',
                'db_table': 'booking_deposit_bank_details',
            },
        ),
    ]
