# Generated by Django 5.2.8 on 2026-08-30 18:35

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0046_depositbankdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsettings',
            name='tourist_tax_max_nights',
            field=models.PositiveIntegerField(default=7, help_text='Maximum number of nights per guest that tourist tax is charged for, regardless of how much longer the actual stay is.'),
        ),
        migrations.AddField(
            model_name='bookingsettings',
            name='tourist_tax_min_age',
            field=models.PositiveIntegerField(default=13, help_text='Age at time of stay (inclusive) from which a guest is liable for tourist tax. Deliberately separate from adult_min_age above - this tracks a municipal tax-law threshold, not a pricing decision, even though both happen to be 13 today.'),
        ),
        migrations.AddField(
            model_name='bookingsettings',
            name='tourist_tax_per_night',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Flat municipal tourist tax charged per qualifying guest, per night.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.CreateModel(
            name='TouristTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('provider', models.CharField(choices=[('revolut', 'Revolut'), ('wise', 'Wise')], default='revolut', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('paid', 'Paid'), ('declined', 'Declined'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('revolut_order_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('revolut_checkout_url', models.URLField(blank=True, null=True)),
                ('last_event_type', models.CharField(blank=True, max_length=100, null=True)),
                ('in_progress_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tourist_tax', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Tourist Tax',
                'verbose_name_plural': 'Tourist Tax',
                'db_table': 'booking_tourist_tax',
            },
        ),
    ]
