# Generated by Django 5.2.8 on 2026-09-04 00:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0047_bookingsettings_tourist_tax_max_nights_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='manual_discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='charge',
            name='manual_discount_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
