# Generated by Django 5.2.8 on 2026-09-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0048_charge_manual_discount_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsettings',
            name='self_check_in_code_reveal_days',
            field=models.PositiveIntegerField(default=2, help_text="How many days before arrival a self-check-in guest's access code(s) become visible on their Manage Booking hub's Location & Arrival page. Before then, a placeholder message is shown instead of the real code(s) - the surrounding instructions (Property.self_check_in_instructions) are unaffected, only the PropertyAccessCode values themselves are withheld."),
        ),
    ]
