# Generated by Django 5.2.8 on 2026-09-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0049_bookingsettings_self_check_in_code_reveal_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrival',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
