# Generated by Django 6.0.1 on 2026-09-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0050_arrival_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsettings',
            name='security_deposits_enabled',
            field=models.BooleanField(default=True, help_text="Master switch for collecting new security deposits. When off, new bookings are created with a €0 deposit regardless of platform/country/owner status (see compute_deposit_waiver()) - existing already-collected deposits (Charge.security already set on a booking) are completely unaffected, and staff can still override Charge.security per booking. Defaults to True so a fresh/test DB keeps today's behavior; the live pause is a data migration on the one production BookingSettings row, not this field default."),
        ),
    ]
