# Generated by Django 5.2.8 on 2026-09-06 18:42

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0050_arrival_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestlistadjustment',
            name='additional_charge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Extra rental+admin cost of the added guest(s) - not part of Charge.', max_digits=8),
        ),
        migrations.CreateModel(
            name='SupplementaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('date_change', 'Date change'), ('guest_add', 'Guest addition')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('EUR', 'EUR'), ('GBP', 'GBP')], max_length=3)),
                ('provider', models.CharField(choices=[('revolut', 'Revolut'), ('wise', 'Wise')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('paid', 'Paid'), ('declined', 'Declined'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('revolut_order_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('revolut_checkout_url', models.URLField(blank=True, null=True)),
                ('last_event_type', models.CharField(blank=True, max_length=100, null=True)),
                ('in_progress_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('new_arrival_date', models.DateField(blank=True, null=True)),
                ('new_departure_date', models.DateField(blank=True, null=True)),
                ('pending_charge_fields', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('pending_guest_rows', models.JSONField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, help_text='When the staged date-change/guest-add was actually applied - distinct from paid_at for the rare case a re-check at apply time fails (see apply()).', null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplementary_payments', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Supplementary payment',
                'db_table': 'booking_supplementary_payments',
            },
        ),
        migrations.AddField(
            model_name='guestlistadjustment',
            name='supplementary_payment',
            field=models.OneToOneField(blank=True, help_text='The online payment that authorized this addition, when additional_charge > 0.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guest_list_adjustment', to='bookings.supplementarypayment'),
        ),
    ]
