# Generated by Django 5.2.8 on 2026-09-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0051_alter_guestlistadjustment_additional_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplementarypayment',
            name='hold_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
