# Generated by Django 6.0.1 on 2026-09-06 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0052_pause_security_deposits'),
        ('bookings', '0052_supplementarypayment_hold_expires_at'),
    ]

    operations = [
    ]
