# Generated by Django 5.2.8 on 2026-09-07 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0053_merge_security_deposit_and_supplementary_payment_branches'),
        ('properties', '0055_property_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalGuideEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('things_to_do', 'Things To Do'), ('beaches', 'Beaches'), ('day_trips', 'Day Trips'), ('dining', 'Where To Eat'), ('shopping', 'Shopping'), ('facilities', 'Local Facilities')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('tag', models.CharField(blank=True, help_text='Short label shown next to the title, e.g. "Formal", "Casual", "45 min drive".', max_length=100)),
                ('description', models.TextField()),
                ('map_link', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('location', models.ForeignKey(blank=True, help_text="Leave blank to show this on every location's Local Guide page.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='local_guide_entries', to='properties.location')),
            ],
            options={
                'verbose_name': 'Local guide entry',
                'verbose_name_plural': 'Local guide entries',
                'db_table': 'local_guide_entries',
                'ordering': ('category', 'order'),
            },
        ),
    ]
