# Generated by Django 5.2.8 on 2026-09-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0054_localguideentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrassettings',
            name='airport_transfer_fallback_contact_name',
            field=models.CharField(blank=True, help_text="Shown to a guest with a booked transfer only if their driver isn't at the meeting point - who they should contact instead. Leave blank to omit this fallback contact from the guest hub entirely.", max_length=100),
        ),
        migrations.AddField(
            model_name='extrassettings',
            name='airport_transfer_fallback_contact_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
