# Generated by Django 6.0.1 on 2026-09-08 01:34

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0054_localguideentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentsettings',
            name='meet_greet_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('28.00'), help_text='Flat fee for a meet & greet, charged whenever one is requested for a stay.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
