# Generated by Django 5.2.8 on 2026-09-08 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0055_alter_paymentsettings_meet_greet_fee'),
        ('bookings', '0055_extrassettings_airport_transfer_fallback_contact_name_and_more'),
    ]

    operations = [
    ]
