# Generated by Django 5.2.8 on 2026-09-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0056_merge_20260908_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='extrassettings',
            name='airport_transfer_cutoff_days_before_arrival',
            field=models.PositiveSmallIntegerField(blank=True, default=3, help_text='Days before arrival that Airport Transfer ordering closes. Blank means no cutoff.', null=True),
        ),
        migrations.AddField(
            model_name='extrassettings',
            name='airport_transfer_last_minute_window_hours',
            field=models.PositiveSmallIntegerField(default=12, help_text='Hours after booking a last-minute reservation still has to request an Airport Transfer.'),
        ),
        migrations.AddField(
            model_name='extrassettings',
            name='cot_high_chair_cutoff_days_before_arrival',
            field=models.PositiveSmallIntegerField(blank=True, default=3, help_text='Days before arrival that Cot/High Chair ordering closes. Blank means no cutoff.', null=True),
        ),
        migrations.AddField(
            model_name='extrassettings',
            name='cot_high_chair_last_minute_window_hours',
            field=models.PositiveSmallIntegerField(default=12, help_text='Hours after booking a last-minute reservation still has to request a Cot/High Chair.'),
        ),
        migrations.AddField(
            model_name='extrassettings',
            name='late_checkout_cutoff_days_before_arrival',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='Days before arrival that Late Checkout ordering closes. Blank (the default) means no cutoff - a guest can request one during their stay.', null=True),
        ),
        migrations.AddField(
            model_name='extrassettings',
            name='late_checkout_last_minute_window_hours',
            field=models.PositiveSmallIntegerField(default=12, help_text='Hours after booking a last-minute reservation still has to request a Late Checkout. Only consulted when a cutoff is actually set.'),
        ),
        migrations.AddField(
            model_name='extrassettings',
            name='mid_stay_clean_cutoff_days_before_arrival',
            field=models.PositiveSmallIntegerField(blank=True, default=3, help_text='Days before arrival that Mid-stay Clean ordering closes. Blank means no cutoff.', null=True),
        ),
        migrations.AddField(
            model_name='extrassettings',
            name='mid_stay_clean_last_minute_window_hours',
            field=models.PositiveSmallIntegerField(default=12, help_text='Hours after booking a last-minute reservation still has to request a Mid-stay Clean.'),
        ),
        migrations.AddField(
            model_name='extrassettings',
            name='welcome_pack_cutoff_days_before_arrival',
            field=models.PositiveSmallIntegerField(blank=True, default=3, help_text='Days before arrival that Welcome Pack ordering closes. Blank means no cutoff.', null=True),
        ),
        migrations.AddField(
            model_name='extrassettings',
            name='welcome_pack_last_minute_window_hours',
            field=models.PositiveSmallIntegerField(default=12, help_text='Hours after booking a last-minute reservation still has to request a Welcome Pack.'),
        ),
        migrations.AddField(
            model_name='requesttype',
            name='cutoff_days_before_arrival',
            field=models.PositiveSmallIntegerField(blank=True, default=3, help_text='Days before arrival that requests for this item close. Blank means no cutoff.', null=True),
        ),
        migrations.AddField(
            model_name='requesttype',
            name='last_minute_window_hours',
            field=models.PositiveSmallIntegerField(default=12, help_text='Hours after booking a last-minute reservation still has to request this item.'),
        ),
    ]
