# Generated by Django 5.2.8 on 2026-09-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0057_booking_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsettings',
            name='tourist_tax_season_end_month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=10, help_text="Last month tourist tax applies to a stay's arrival date (inclusive)."),
        ),
        migrations.AddField(
            model_name='bookingsettings',
            name='tourist_tax_season_start_month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=4, help_text="First month tourist tax applies to a stay's arrival date (inclusive)."),
        ),
    ]
