# Generated by Django 5.2.8 on 2026-09-09 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0058_bookingsettings_tourist_tax_season_end_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsettings',
            name='cleaning_gap_nights_per_block_day',
            field=models.PositiveIntegerField(default=0, help_text='For every N nights a confirmed stay lasts, one extra day right after departure is blocked from booking (only into a real gap before the next confirmed arrival, capped at that gap) so the cleaning crew gets more time on long stays. 0 disables this.'),
        ),
    ]
