# Generated by Django 5.2.8 on 2026-09-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0059_bookingsettings_cleaning_gap_nights_per_block_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsettings',
            name='wise_payment_link',
            field=models.URLField(blank=True, help_text="Informal Wise payment link to share with an owner alongside their outstanding balance. Not yet referenced by any automated email - for staff to copy/paste manually until that's built.", null=True),
        ),
    ]
