# Generated by Django 5.2.8 on 2026-09-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0060_paymentsettings_wise_payment_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
