# Generated by Django 5.2.8 on 2026-09-13 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0061_booking_terms_accepted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reservation group',
                'verbose_name_plural': 'Reservation groups',
                'db_table': 'reservation_groups',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='reservation_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.reservationgroup'),
        ),
    ]
