# Generated by Django 5.2.8 on 2026-09-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0062_reservation_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrival',
            name='time_unknown',
            field=models.BooleanField(default=False),
        ),
    ]
