# Generated by Django 5.2.8 on 2026-09-15 07:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0064_backfill_arrival_time_unknown'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='sibling_cancellation_credit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Deposit carried over from a cancelled sibling apartment of the same reservation.', max_digits=10),
        ),
    ]
