# Generated by Django 5.2.8 on 2026-09-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0065_charge_sibling_cancellation_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra',
            name='no_extras_confirmed',
            field=models.BooleanField(default=False, help_text="Guest ticked 'I confirm I don't want any extras' on the Manage Booking hub - lets the hub's progress checklist tell 'genuinely nothing wanted' apart from 'hasn't looked yet', since this section has no other way to reach a done state."),
        ),
    ]
