# Generated by Django 5.2.8 on 2026-09-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0066_extra_no_extras_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsettings',
            name='max_advance_booking_months',
            field=models.PositiveIntegerField(default=18, help_text="How far in advance (in months, from today) the public site accepts a guest search or reservation. Doesn't affect staff-created owner bookings, guest offers, or property blocks."),
        ),
    ]
