# Generated by Django 5.2.8 on 2026-09-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0067_bookingsettings_max_advance_booking_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsettings',
            name='company_bank_account_holder_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='company_bank_iban',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='company_bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='company_bank_swift_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
