# Generated by Django 5.2.8 on 2026-09-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0068_paymentsettings_company_bank_account_holder_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsettings',
            name='company_bank_address',
            field=models.CharField(blank=True, help_text="The bank's own address - often required alongside SWIFT/BIC for an international wire transfer, same as company_bank_name/iban/swift_code.", max_length=255, null=True),
        ),
    ]
