# Generated by Django 5.2.8 on 2026-09-17 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0069_paymentsettings_company_bank_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentsettings',
            name='charge_vat_on_low_season_direct_commission',
        ),
        migrations.RemoveField(
            model_name='paymentsettings',
            name='charge_vat_on_low_season_platform_commission',
        ),
    ]
